//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "follow")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub src_id: i64,
  #[sea_orm(primary_key, auto_increment = false)]
  pub dst_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::DstId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User2,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::SrcId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User1,
}

impl ActiveModelBehavior for ActiveModel {}
