//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::comment::Entity as Comment;
pub use super::favorite::Entity as Favorite;
pub use super::like::Entity as Like;
pub use super::media::Entity as Media;
pub use super::media_tag::Entity as MediaTag;
pub use super::subscribe::Entity as Subscribe;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
